nelmio_api_doc:
    documentation:
        info:
            title: My symfony API
            description: this is my test API
            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api # Accepts routes under /api except /api/doc
            - ^/me
            - ^/token