trikoder_oauth2:
  authorization_server:
    private_key: C:\GitHub\test\test\var\oauth\private.key

    private_key_passphrase: null

    encryption_key: XyS7pS1PBkwCVnZBYogJig8HjDRUUSptOdc3ODwT2yY=

    encryption_key_type: plain

    access_token_ttl: PT12H

    refresh_token_ttl: P1M

    auth_code_ttl: ~

    require_code_challenge_for_public_clients: ~

    enable_auth_code_grant: ~

    enable_client_credentials_grant: ~

    enable_implicit_grant: ~

    enable_password_grant: true

    enable_refresh_token_grant: ~

    grant_types:
      authorization_code:
        enable: true

        access_token_ttl: PT12H

        refresh_token_ttl: PT12H

        auth_code_ttl: PT10M

        require_code_challenge_for_public_clients: true

      client_credentials:
        enable: ~

        access_token_ttl: ~

      implicit:
        enable: ~

        access_token_ttl: ~

      password:
        enable: true

        access_token_ttl: PT1H

        refresh_token_ttl: PT1H

      refresh_token:
        enable: true

        access_token_ttl: PT1H

        refresh_token_ttl: PT1H

  resource_server: # Required
    public_key: C:\GitHub\test\test\var\oauth\public.key

  scopes: [read, create]

  persistence: # Required
    doctrine:
      entity_manager: default
  #        in_memory:            ~

  exception_event_listener_priority: 10

  role_prefix: ROLE_OAUTH2_
