parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\EventListeners\UserResolveListener:
        arguments:
          - '@App\Repository\UserRepository'
          - '@security.password_encoder'
        tags:
          - { name: kernel.event_listener, event: trikoder.oauth2.user_resolve, method: onUserResolve }    


    League\OAuth2\Server\ResourceServer:
      arguments:
        $accessTokenRepository: '@Trikoder\Bundle\OAuth2Bundle\League\Repository\AccessTokenRepository'
        $publicKey: '%env(OAUTH2_PUBLIC_KEY)%'
